apiVersion: argoproj.io/v1alpha1 
kind: Application 
metadata: 
  name: sealed-secrets 
  namespace: argocd
spec: 
  project: default 
  source: 
    chart: sealed-secrets 
    repoURL: https://charts.bitnami.com/bitnami 
    targetRevision: 1.0.10
    helm: 
      releaseName: sealed-secrets 
  destination: 
    server: "https://kubernetes.default.svc" 
    namespace: sealed-secrets
  syncPolicy: 
    automated: 
      prune: true 
      selfHeal: true 
    syncOptions: 
    - CreateNamespace=true